apiVersion: v1
kind: Service
metadata:
  name: scrollarr
  labels:
    app: scrollarr
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
  selector:
    app: scrollarr
  type: ClusterIP
